r2dbc:
  datasource:
    host: localhost
    database: reservation
    username: root
    password: root

logging:
  level:
    root: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS